"""HA & firewall2 recovery analyzer: HA-001 through HA-009."""

from __future__ import annotations

from opn_boss.analyzers.base import BaseAnalyzer
from opn_boss.core.types import Category, CollectorResult, Finding, Severity


class HaRecoveryAnalyzer(BaseAnalyzer):
    category = "ha_recovery"

    # Remediation text for RA conflict (HA-004)
    RA_CONFLICT_REMEDIATION = """Router Advertisement (RA) Conflict Detected on firewall2.

CAUSE: firewall2's radvd service is sending IPv6 Router Advertisement packets on the LAN,
competing with the primary router and causing IPv6 connectivity issues for LAN clients.

REMEDIATION STEPS:
1. Access firewall2's OPNSense WebGUI directly at its management IP.
2. Navigate to Services → Router Advertisements.
3. For each LAN interface listed:
   a. Click the interface name to open settings.
   b. Set "Router Advertisements" to "Disabled".
   c. Save and apply.
4. Alternatively, navigate to Services → DHCPv6 and disable it on LAN interfaces.
5. Verify: After disabling, IPv6 clients should receive RA only from the primary router.
6. If firewall2 is still causing conflicts, consider:
   - Disabling IPv6 entirely on firewall2's LAN interfaces.
   - Setting firewall2's LAN interface to "None" for IPv6 configuration mode.

VALIDATION: Run 'rtsol -D em0' or check 'ip -6 route' on a LAN client to confirm
only one default IPv6 gateway is advertised.
"""

    def analyze(
        self,
        firewall_id: str,
        collector_results: dict[str, CollectorResult],
    ) -> list[Finding]:
        findings: list[Finding] = []
        carp = self._get_data(collector_results, "carp")
        interfaces = self._get_data(collector_results, "interfaces")
        system = self._get_data(collector_results, "system")

        # HA-001 is generated by the service layer when fw2 is unreachable,
        # but we can also check it here if we have state info
        findings += self._ha002_carp_fault(firewall_id, carp)
        findings += self._ha003_split_brain(firewall_id, carp)
        findings += self._ha004_ra_conflict(firewall_id, carp, interfaces)
        findings += self._ha005_advskew_mismatch(firewall_id, carp)
        findings += self._ha006_config_sync(firewall_id, system)
        findings += self._ha007_pfsync_disabled(firewall_id, carp)
        findings += self._ha008_last_seen(firewall_id, system)
        findings += self._ha009_vip_count(firewall_id, carp)

        return findings

    def _ha002_carp_fault(self, firewall_id: str, carp: dict) -> list[Finding]:
        if not carp:
            return []
        status = carp.get("carp_status", "").upper()
        if status in ("INIT", "FAULT"):
            return [Finding(
                check_id="HA-002",
                title=f"CARP is in {status} state",
                description=(
                    f"CARP on {firewall_id} is reporting status '{status}'. "
                    "This indicates HA is not functioning correctly. "
                    "The firewall may not be participating in high availability."
                ),
                severity=Severity.WARNING,
                category=Category.HA_RECOVERY,
                firewall_id=firewall_id,
                evidence={"carp_status": status},
                remediation=(
                    "Check CARP settings under Interfaces → Virtual IPs. "
                    "Ensure both firewalls can communicate on the CARP interface. "
                    "Verify that pfsync is enabled and the sync interface is up."
                ),
            )]
        if status == "MASTER":
            return [Finding(
                check_id="HA-002",
                title="CARP is MASTER",
                description=f"{firewall_id} is the active CARP master.",
                severity=Severity.OK,
                category=Category.HA_RECOVERY,
                firewall_id=firewall_id,
                evidence={"carp_status": status},
            )]
        if status == "BACKUP":
            return [Finding(
                check_id="HA-002",
                title="CARP is BACKUP",
                description=f"{firewall_id} is the standby CARP backup.",
                severity=Severity.OK,
                category=Category.HA_RECOVERY,
                firewall_id=firewall_id,
                evidence={"carp_status": status},
            )]
        return []

    def _ha003_split_brain(self, firewall_id: str, carp: dict) -> list[Finding]:
        """Detect if this firewall is MASTER while we also know another is MASTER."""
        # This check is most meaningful when comparing two firewalls.
        # Here we flag if CARP reports MASTER without a backup being known.
        status = carp.get("carp_status", "").upper()
        if status == "MASTER":
            # Check VIPs — if any VIP is also MASTER, that's expected for primary.
            # We emit INFO for audit purposes.
            return [Finding(
                check_id="HA-003",
                title="CARP MASTER — verify no split-brain",
                description=(
                    f"{firewall_id} is CARP MASTER. If firewall2 is also MASTER "
                    "(split-brain), both firewalls will process traffic independently, "
                    "causing network instability and duplicate connections."
                ),
                severity=Severity.INFO,
                category=Category.HA_RECOVERY,
                firewall_id=firewall_id,
                evidence={"carp_status": status},
                remediation=(
                    "Verify firewall2 shows CARP BACKUP status. "
                    "If both show MASTER, check pfsync connectivity and CARP advskew values."
                ),
            )]
        return []

    def _ha004_ra_conflict(
        self, firewall_id: str, carp: dict, interfaces: dict
    ) -> list[Finding]:
        """Detect IPv6 RA conflict — the key finding for firewall2 recovery."""
        # If CARP plugin is not installed, skip this check entirely —
        # no CARP means no HA pair, so RA conflict is not a concern.
        if not carp.get("carp_available", True):
            return []

        carp_status = carp.get("carp_status", "").upper()

        # Check for ICMPv6 RA packets in interface stats
        ifaces = interfaces.get("interfaces", {})
        ra_senders: list[str] = []
        for iface_name, iface_data in ifaces.items():
            if not isinstance(iface_data, dict):
                continue
            # Look for ICMPv6 type 134 (Router Advertisement) outbound
            # Some OPNSense versions expose this in interface stats
            icmpv6_out = iface_data.get("icmp6_output", 0)
            if isinstance(icmpv6_out, (int, float)) and icmpv6_out > 0:
                ra_senders.append(iface_name)

        # Fire if: CARP is INIT/FAULT (circumstantial evidence of conflict)
        # OR if we detect RA output on interfaces (direct evidence)
        # Do NOT fire on empty/unknown status — that just means CARP isn't reporting.
        carp_troubled = carp_status in ("INIT", "FAULT")
        has_ra_evidence = bool(ra_senders)

        if carp_troubled or has_ra_evidence:
            evidence: dict = {
                "carp_status": carp_status,
                "ra_sending_interfaces": ra_senders,
            }
            if has_ra_evidence:
                severity = Severity.CRITICAL
                desc = (
                    f"IPv6 Router Advertisement conflict detected on {firewall_id}. "
                    f"Interfaces {ra_senders} are sending RA packets, which may conflict "
                    "with the primary firewall's RA, causing IPv6 connectivity issues for "
                    "all LAN clients."
                )
            else:
                severity = Severity.WARNING
                desc = (
                    f"Potential IPv6 RA conflict on {firewall_id} (CARP status: {carp_status}). "
                    "When CARP is not functioning correctly, radvd may send conflicting "
                    "Router Advertisements on LAN interfaces."
                )
            return [Finding(
                check_id="HA-004",
                title="IPv6 Router Advertisement conflict detected",
                description=desc,
                severity=severity,
                category=Category.HA_RECOVERY,
                firewall_id=firewall_id,
                evidence=evidence,
                remediation=self.RA_CONFLICT_REMEDIATION,
            )]
        return []

    def _ha005_advskew_mismatch(self, firewall_id: str, carp: dict) -> list[Finding]:
        """Check CARP advertising skew values."""
        if not carp:
            return []
        vips = carp.get("vips", {})
        if not vips:
            return []

        # Collect skew values
        skews: list[int] = []
        if isinstance(vips, dict):
            for vip in vips.values():
                if isinstance(vip, dict):
                    try:
                        skews.append(int(vip.get("advskew", 0)))
                    except (ValueError, TypeError):
                        pass
        elif isinstance(vips, list):
            for vip in vips:
                if isinstance(vip, dict):
                    try:
                        skews.append(int(vip.get("advskew", 0)))
                    except (ValueError, TypeError):
                        pass

        if not skews:
            return []

        # All VIPs on the same firewall should have consistent relative skew
        unique_skews = set(skews)
        if len(unique_skews) > 1:
            return [Finding(
                check_id="HA-005",
                title="CARP advskew values are inconsistent across VIPs",
                description=(
                    f"Virtual IPs have different advskew values: {sorted(unique_skews)}. "
                    "Inconsistent skew can cause unpredictable MASTER/BACKUP elections."
                ),
                severity=Severity.WARNING,
                category=Category.HA_RECOVERY,
                firewall_id=firewall_id,
                evidence={"skew_values": sorted(unique_skews)},
                remediation=(
                    "Set consistent advskew values across all VIPs. "
                    "Primary firewall: advskew=0, backup firewall: advskew=100."
                ),
            )]
        return []

    def _ha006_config_sync(self, firewall_id: str, system: dict) -> list[Finding]:
        """Check for config sync status (informational)."""
        if not system:
            return []
        # Look for any sync-related fields in system status
        sync_status = system.get("config_sync", "")
        if sync_status and "error" in str(sync_status).lower():
            return [Finding(
                check_id="HA-006",
                title="Configuration synchronization error",
                description=(
                    "The firewall reports a configuration sync error. "
                    "The backup firewall may have an outdated configuration."
                ),
                severity=Severity.WARNING,
                category=Category.HA_RECOVERY,
                firewall_id=firewall_id,
                evidence={"sync_status": sync_status},
                remediation=(
                    "Navigate to System → High Availability → Settings and "
                    "trigger a manual configuration sync."
                ),
            )]
        return []

    def _ha007_pfsync_disabled(self, firewall_id: str, carp: dict) -> list[Finding]:
        """Check if pfsync (state sync) appears disabled."""
        if not carp:
            return []
        # If CARP exists but pfsync info is absent, it may be disabled
        # This is a best-effort check
        pfsync = carp.get("pfsync", "")
        if pfsync == "disabled" or pfsync == "0":
            return [Finding(
                check_id="HA-007",
                title="pfsync (connection state sync) appears disabled",
                description=(
                    "pfsync does not appear to be active. Without state synchronization, "
                    "existing connections will drop on a CARP failover event."
                ),
                severity=Severity.WARNING,
                category=Category.HA_RECOVERY,
                firewall_id=firewall_id,
                remediation=(
                    "Enable pfsync under System → High Availability → Settings. "
                    "Ensure both firewalls have a dedicated pfsync interface."
                ),
            )]
        return []

    def _ha008_last_seen(self, firewall_id: str, system: dict) -> list[Finding]:
        """Check uptime — a very short uptime suggests a recent unexpected reboot."""
        if not system:
            return []
        uptime_sec = system.get("uptime_seconds", None)
        if uptime_sec is None:
            return []
        try:
            uptime_sec = float(uptime_sec)
        except (ValueError, TypeError):
            return []

        # uptime_sec == 0 means we couldn't retrieve it — don't fire
        if uptime_sec == 0:
            return []

        if uptime_sec < 300:  # under 5 minutes
            return [Finding(
                check_id="HA-008",
                title="Very short uptime — likely just rebooted",
                description=(
                    f"Uptime is only {uptime_sec:.0f} seconds. "
                    "The firewall may have recently crashed or been rebooted unexpectedly."
                ),
                severity=Severity.WARNING,
                category=Category.HA_RECOVERY,
                firewall_id=firewall_id,
                evidence={"uptime_seconds": uptime_sec},
                remediation=(
                    "Check system logs under System → Log Files → System "
                    "for crash or reboot reasons."
                ),
            )]
        return []

    def _ha009_vip_count(self, firewall_id: str, carp: dict) -> list[Finding]:
        """Flag if VIP count is zero — HA is not configured."""
        # If CARP is simply not installed, don't flag this
        if not carp or not carp.get("carp_available", True):
            return []
        vips = carp.get("vips", {})
        count = 0
        if isinstance(vips, dict):
            count = len(vips)
        elif isinstance(vips, list):
            count = len(vips)

        if count == 0:
            return [Finding(
                check_id="HA-009",
                title="No CARP Virtual IPs configured",
                description=(
                    "No CARP Virtual IPs (VIPs) are configured. "
                    "High availability requires at least one VIP per HA-active interface."
                ),
                severity=Severity.INFO,
                category=Category.HA_RECOVERY,
                firewall_id=firewall_id,
                remediation=(
                    "Configure CARP VIPs under Interfaces → Virtual IPs. "
                    "Add a VIP for each interface that should fail over."
                ),
            )]
        return []
